Repository riskledger/update-pr-description, pull requests merged in 2020-06, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation

#2 Update branding
  action.yml
Labels: internal

#6 Change PR number fetch + fix octokit usage
  main.js
Labels: Internal

#7 SPAGhetti
  README.md
Labels: Bug, Documentation
